name: conformaltree
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - blas=2.122
  - blas-devel=3.9.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cairo=1.16.0
  - catboost=1.2.3
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - cython=3.0.10
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - filelock=3.13.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.1.2
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=73.1
  - idna=3.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libtool=2.4.6
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lightgbm=4.1.0
  - llvm-openmp=18.1.3
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.27
  - openjpeg=2.3.0
  - openssl=3.0.13
  - packaging=24.0
  - pandas=2.2.1
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.40.0
  - platformdirs=4.2.0
  - plotly=5.19.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0
  - python-graphviz=0.20.1
  - python-tzdata=2023.3
  - pytorch=2.2.2
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.31.0
  - scipy=1.12.0
  - seaborn=0.12.2
  - setuptools=69.2.0
  - six=1.16.0
  - sqlite=3.45.2
  - stack_data=0.6.2
  - sympy=1.12
  - tenacity=8.2.2
  - tk=8.6.13
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.14.2
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - joblib==1.4.0
      - scikit-learn==1.4.2
      - sklearn-quantile==0.0.30
      - threadpoolctl==3.4.0
